services:
  - type: web
    name: emergeai-backend
    env: python
    rootDir: .
    buildCommand: pip install -r backend/requirements.txt
    startCommand: python -m uvicorn backend.main:app --host 0.0.0.0 --port $PORT

    envVars:
      - key: HOST
        value: 0.0.0.0

      - key: RELOAD
        value: false

      - key: SECRET_KEY
        sync: false

      - key: DATABASE_URL
        sync: false

      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 60

      # Set this in Render dashboard to: https://emergeai-frontend.onrender.com
      - key: CORS_ORIGINS
        sync: false

      - key: RENDER
        value: true

      - key: MODEL_PATH
        value: models/triage_xgboost_balanced.pkl

      - key: FEATURE_COLUMNS_PATH
        value: models/emergency_feature_columns.pkl

  - type: web
    name: emergeai-frontend
    env: python
    rootDir: .
    buildCommand: pip install -r frontend/requirements.txt
    startCommand: streamlit run frontend/app.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      # Set this in Render dashboard to: https://emergeai-backend.onrender.com
      - key: API_URL
        sync: false

      - key: RENDER
        value: true
